server:
  port: 8989

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.coffit.today:1521:xe
    username: C##INFOMATE
    password: INFOMATE
    hikari:
      auto-commit: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/productimgs/

  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
#        hibernate:
#          ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 20 #페이지 사이즈(default)
        max-page-size: 50 # max 사이즈

  profiles:
    active: local

jwt:
  secret: 1LxrVXYDdRoBBa2Wc9lfOLVUl9BXt6JEZEhkm1mLY04lbjIx4I18x4QOha7cSKrCQJCKwpavnVtfVzFPnBzJfQ==

logging:
  level:
    root: info

image:
  add-resource-locations: classpath:/static/productimgs/
  add-resource-handler: /productimgs/**

  image-dir: src/main/resources/static/productimgs
  image-url: http://localhost:8989/productimgs/


