### 로그인
POST http://localhost:8989/auth/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "memberId": "user1",
  "memberPassword": "user1"
}

### 회원가입
POST http://localhost:8989/auth/signup
Content-Type: application/json
Accept: */*

{
  "memberPassword": "user1",
  "memberName": "아무개",
  "memberId": "user1",
  "memberEmail": "a@mugae.com",
  "memberPhone": "010-4324-1234",
  "memberNo": "1999-01-23",
  "memberStatus": "Y",
  "memberAddress": "경기도 고양시 일산동구",
  "hireDate": "2023-08-28T12:00:00Z",
  "department": {
    "deptCode": 3
  },
  "rankCode": 2,
  "memberOff": 12
}