### 로그인
POST http://localhost:8989/auth/login
Content-Type: application/json
Accept: */*
Access-Control-Allow-Origin: *

{
  "memberId": "num5",
  "memberPassword": "num5"
}

### 회원가입
POST http://localhost:8989/auth/signup
Content-Type: application/json
Accept: */*

{
  "memberPassword": "num5",
  "memberName": "주인5",
  "memberId": "num5",
  "memberEmail": "num5@num5.com",
  "memberPhone": "010-5555-5555",
  "memberNo": "1947-05-05",
  "memberStatus": "Y",
  "memberAddress": "서울특별시 종로구",
  "hireDate": "1999-08-28T12:00:00Z",
  "department": {
    "deptCode": 1
  },
  "rankCode": 1,
  "memberOff": 12
}