CREATE SEQUENCE SEQ_TBL_APPROVAL_APPROVAL_ID     INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_AUTHORITY_AUTHORITY_CODE  INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_BOARD_BOARD_CODE      INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_BOARDFILE_FILE_NO         INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_CLNDR_CLNDR_CODE;
CREATE SEQUENCE SEQ_TBL_COMMENT_COMMENT_CODE    INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_CONTACT_CONTACT_CODE    INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_DEPT_DEPT_CODE       INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_DOCFILE_FILE_CODE       INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_DOCUMENT_DOCUMENT_ID     INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_FVRT_CLNDR_FVRT_CLNDR_ID;
CREATE SEQUENCE SEQ_TBL_MAIL_MAIL_CODE       INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_MEMBER_MEMBER_CODE     INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_OFF_OFF_CODE        INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_PAYMENTLIST_PAYMENT_CODE        INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_PHOTO_FILE_FILE_CODE       INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_POST_POST_CODE       INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_RANK_RANK_CODE       INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_REFERENCE_REFERENCE_CODE  INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_SCHDL_SCHDL_ID        INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_TRASH_TRASH_CODE      INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_VACATION_DOCUMENT_ID     INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_WORK_WORK_CODE       INCREMENT BY 1 ;
CREATE SEQUENCE SEQ_TBL_DOCREF_REF_CODE       INCREMENT BY 1 ;


COMMIT ;
