ALTER TABLE TBL_SCHDL
    DROP CONSTRAINT TBL_SCHDL_REF_CLNDR_ID_FK;

ALTER TABLE TBL_SCHDL
    ADD CONSTRAINT TBL_SCHDL_REF_CLNDR_ID_FK FOREIGN KEY (REF_CLNDR_ID) REFERENCES TBL_CLNDR (CLNDR_CODE);

ALTER TABLE TBL_APPROVAL
    ADD CONSTRAINT TBL_APPROVAL_TBL_MEMBER_FK
        FOREIGN KEY (MEMBER_CODE) REFERENCES TBL_MEMBER (MEMBER_CODE);

ALTER TABLE TBL_APPROVAL
    ADD CONSTRAINT TBL_APPROVAL_TBL_DOCUMENT_FK
        FOREIGN KEY (DOCUMENT_ID) REFERENCES TBL_DOCUMENT (DOCUMENT_ID);

ALTER TABLE TBL_DOCFILE
    ADD CONSTRAINT TBL_DOCFILE_TBL_DOCUMENT_FK
        FOREIGN KEY (DOCUMENT_ID) REFERENCES TBL_DOCUMENT (DOCUMENT_ID);

ALTER TABLE TBL_DOCREF
    ADD CONSTRAINT TBL_DOCREF_TBL_DOCUMENT_FK
        FOREIGN KEY (DOCUMENT_ID) REFERENCES TBL_DOCUMENT (DOCUMENT_ID);

ALTER TABLE TBL_DOCREF
    ADD CONSTRAINT TBL_DOCREF_TBL_MEMBER_FK
        FOREIGN KEY (MEMBER_CODE) REFERENCES TBL_MEMBER (MEMBER_CODE);

ALTER TABLE TBL_DOCUMENT
    ADD CONSTRAINT TBL_DOCUMENT_TBL_MEMBER_FK
        FOREIGN KEY (MEMBER_CODE) REFERENCES TBL_MEMBER (MEMBER_CODE);

ALTER TABLE TBL_PAYMENT
    ADD CONSTRAINT TBL_PAYMENT_FK
        FOREIGN KEY (DOCUMENT_ID) REFERENCES TBL_DOCUMENT;

ALTER TABLE TBL_PAYMENTLIST
    ADD CONSTRAINT TBL_PAYMENTLIST_TBL_PAYMENT_FK
        FOREIGN KEY (DOCUMENT_ID) REFERENCES TBL_PAYMENT;

ALTER TABLE TBL_VACATION
    ADD CONSTRAINT TBL_VACATION_TBL_DOCUMENT_FK
        FOREIGN KEY (DOCUMENT_ID) REFERENCES TBL_DOCUMENT;

ALTER TABLE TBL_DRAFT
    ADD CONSTRAINT TBL_DRAFT_PK PRIMARY KEY ( DOCUMENT_ID )
    USING INDEX TBL_DRAFT_PK;